/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Negocios.ClsEEmpleado;
import Negocios.ClsNEmpleado;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stryker
 */
public class Empleado extends javax.swing.JPanel {

    /**
     * Creates new form Empleado
     */
    DefaultTableModel tbmodelo=new DefaultTableModel();
    public Empleado() {
        initComponents();
        tbmodelo.addColumn("DNI");
        tbmodelo.addColumn("NOMBRE");
        tbmodelo.addColumn("APELLIDO");
        tbmodelo.addColumn("DIRECCION");
        tbmodelo.addColumn("TELEFONO");
        tbmodelo.addColumn("EMAIL");
        tbmodelo.addColumn("CARGO");
        tblempleado.setModel(tbmodelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtDni = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtCargo = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblempleado = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        TxtBuscardni = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE EMPLEADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel2.setText("DNI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("APELLIDO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setText("DIRECCION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText("EMAIL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setText("TELEFONO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel8.setText("CARGO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel1.add(TxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, -1));
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, -1));
        jPanel1.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, -1));
        jPanel1.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, -1));
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, -1));
        jPanel1.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 140, -1));
        jPanel1.add(TxtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 140, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        BtnEliminar.setText("Eliminar");
        jPanel1.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        BtnListar.setText("Listar");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        tblempleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblempleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 112, 500, 410));

        jLabel9.setText("BUSCAR DNI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));
        jPanel1.add(TxtBuscardni, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 150, -1));

        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:\
        TxtDni.setText("");
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtDireccion.setText("");
        TxtEmail.setText("");
        TxtTelefono.setText("");
        TxtCargo.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
         ClsEEmpleado objECli =new ClsEEmpleado();
        ClsNEmpleado objNCli = new ClsNEmpleado();
        objECli.setDni(TxtDni.getText());
        objECli.setNombre(TxtNombre.getText());
        objECli.setApellido(TxtApellido.getText());
        objECli.setDireccion(TxtDireccion.getText());
        objECli.setEmail(TxtEmail.getText());
        objECli.setTelefono(TxtTelefono.getText());
        objECli.setCargo(TxtCargo.getText());

        if (objNCli.MtdAgregarEmpleado(objECli))
        {
            JOptionPane.showMessageDialog(null,"Empleado guardado");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ERROR de Empleado");
        }

    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        ClsEEmpleado objECli =new ClsEEmpleado();
        ClsNEmpleado objNCli = new ClsNEmpleado();
        objECli.setDni(TxtDni.getText());
        objECli.setNombre(TxtNombre.getText());
        objECli.setApellido(TxtApellido.getText());
        objECli.setDireccion(TxtDireccion.getText());
        objECli.setEmail(TxtEmail.getText());
        objECli.setTelefono(TxtTelefono.getText());
        objECli.setCargo(TxtCargo.getText());

        if (objNCli.MtdEditarEmpleado(objECli))
        {
            JOptionPane.showMessageDialog(null,"Empleado Actualizado");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ERROR de Empleado");
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed
        // TODO add your handling code here:
         ResultSet rs=null;
        ClsNEmpleado objNCli = new ClsNEmpleado();
        rs=objNCli.MtdListarEmpleados();
        String[] dato=new String[7];
        
        limpiar();
        try {
            while(rs.next())
            {
                dato[0]=rs.getString("dni_emp");
                dato[1]=rs.getString("nombre_emp");
                dato[2]=rs.getString("apellido_emp");
                dato[3]=rs.getString("direccion_emp");
                dato[4]=rs.getString("telefono_emp");
                dato[5]=rs.getString("email_emp");
                dato[6]=rs.getString("cargo_emp");
                //System.out.println("el valor de dni es"+rs.getString("dni"));
                tbmodelo.addRow(dato);
            }
            tblempleado.setModel(tbmodelo);
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnListarActionPerformed

    private void limpiar(){
        for(int i = 0; i < tblempleado.getRowCount(); i++){
            tbmodelo.removeRow(i);
            i = i-1;
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnListar;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtBuscardni;
    private javax.swing.JTextField TxtCargo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblempleado;
    // End of variables declaration//GEN-END:variables
}
