/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Negocios.ClsEProducto;
import Negocios.ClsNProducto;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stryker
 */
public class Producto extends javax.swing.JPanel {

    /**
     * Creates new form Producto
     */
    DefaultTableModel tbmodelo = new DefaultTableModel();
    public Producto() {
        initComponents();tbmodelo.addColumn("ID");
        tbmodelo.addColumn("NOMBRE");
        tbmodelo.addColumn("DESCRIPCION");
        tbmodelo.addColumn("PRECIO");
        tbmodelo.addColumn("STOCK");
        
        tblProducto.setModel(tbmodelo);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        txtimagen = new javax.swing.JTextField();
        btnseleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lblfoto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbuscarid = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE PRODUCTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("DESCRIPCION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setText("PRECIO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("STOCK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("IMAGEN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 30, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 210, -1));
        jPanel1.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 210, -1));
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, -1));
        jPanel1.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 140, -1));
        jPanel1.add(txtimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, -1));

        btnseleccionar.setText("SELECCIONAR");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnseleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 490, 390));

        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel1.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        lblfoto.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 190, 130));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("BUSCAR ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));
        jPanel1.add(txtbuscarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 120, -1));

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        
        limpiar();
        limpiarcajas();
        listar();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        
         ClsNProducto objNPro = new ClsNProducto();
        ClsEProducto objEPro = new ClsEProducto();
        
        objEPro.setId_pro(Integer.parseInt(txtid.getText()));
        objEPro.setNombre_pro(txtnombre.getText());
        objEPro.setImagen(txtimagen.getText());
        objEPro.setDescripcion_pro(txtdescripcion.getText());
        objEPro.setPrecio_pro(Double.valueOf(txtprecio.getText()));
        objEPro.setStock_pro(Integer.parseInt(txtstock.getText()));
        
        if (objNPro.MtdAgregarProducto(objEPro))
        {
            JOptionPane.showMessageDialog(null, "Cliente Guardado");
            limpiar();
            limpiarcajas();
            listar();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");            
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
         ClsNProducto objNPro = new ClsNProducto();
        ClsEProducto objEPro = new ClsEProducto();
        
        objEPro.setId_pro(Integer.parseInt(txtid.getText()));
        objEPro.setNombre_pro(txtnombre.getText());
        objEPro.setDescripcion_pro(txtdescripcion.getText());
        objEPro.setPrecio_pro(Double.valueOf(txtprecio.getText()));
        objEPro.setStock_pro(Integer.parseInt(txtstock.getText()));
        
        if (objNPro.MtdEditarProducto(objEPro))
        {
            JOptionPane.showMessageDialog(null, "Cliente Actualizado");
            limpiar();
            limpiarcajas();
            listar();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");            
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        ClsNProducto objNPro = new ClsNProducto();
        ClsEProducto objEPro = new ClsEProducto();
        
        objEPro.setId_pro(Integer.parseInt(txtid.getText()));
        
        if (objNPro.MtdEliminarProducto(objEPro))
        {
            JOptionPane.showMessageDialog(null, "Producto Eliminado");
            limpiar();
            limpiarcajas();
            listar();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");            
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de archivos JPEG(*.JPG;*.JPEG,*.PNG)","jpg","jpeg","png");
        
        JFileChooser archivo = new JFileChooser();
        
        archivo.addChoosableFileFilter(filtro);
        
        archivo.setDialogTitle("Abrir archivo");
        File ruta = new File("C:/Users/USUARIO/Downloads/apache-tomcat-9.0.55/webapps/imagenes");
        
        archivo.setCurrentDirectory(ruta);
        
        int ventana = archivo.showOpenDialog(null);
        
        if (ventana == JFileChooser.APPROVE_OPTION){
            File file = archivo.getSelectedFile();
            txtimagen.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(txtimagen.getText());
            foto = foto.getScaledInstance(150, 150, Image.SCALE_DEFAULT);
            lblfoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        ClsNProducto objNP = new ClsNProducto();
        ClsEProducto objEP = new ClsEProducto();
        JFileChooser archivo = new JFileChooser();
        objEP.setId_pro(Integer.parseInt(txtbuscarid.getText()));
        ResultSet rs;
        rs=objNP.MtdBuscarId(objEP);
        limpiar();
        if(rs!=null){
            try {
                String[] dato=new String[6]; 
                while (rs.next()) 
                {
                dato[0]=String.valueOf(rs.getInt("id_pro"));
                dato[1]=rs.getString("nombre_pro");
                dato[2]=rs.getString("descripcion_pro");
                dato[3]=String.valueOf(rs.getDouble("precio_pro"));
                dato[4]=String.valueOf(rs.getInt("stock_pro"));
                dato[5]=rs.getString("imagen_pro");
                
                tbmodelo.addRow(dato);
                
                txtid.setText(dato[0]);
                txtnombre.setText(dato[1]);
                txtdescripcion.setText(dato[2]);
                txtprecio.setText(dato[3]);
                txtstock.setText(dato[4]);
                txtimagen.setText(dato[5]);
                
            }
              
              tblProducto.setModel(tbmodelo);  
            } catch (Exception e) {
                System.out.println("error "+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        // TODO add your handling code here:
         int fila = tblProducto.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "usuario no seleccionado");
        }else{
            int id=Integer.parseInt((String)tblProducto.getValueAt(fila, 0).toString());
            String nombre =(String)tbmodelo.getValueAt(fila, 1);
            String descripcion=(String)tbmodelo.getValueAt(fila, 2);
            Double stock = Double.valueOf((String)tbmodelo.getValueAt(fila, 3).toString());
            int precio=Integer.parseInt((String)tblProducto.getValueAt(fila, 4).toString());
            
            txtid.setText(""+id);
            txtnombre.setText(nombre);
            txtdescripcion.setText(descripcion);
            txtprecio.setText(""+stock);
            txtstock.setText(""+precio);
        }
    }//GEN-LAST:event_tblProductoMouseClicked

    void listar(){
        ResultSet rs=null;
        ClsNProducto objNPro = new ClsNProducto();
        rs = objNPro.MtdListarProducto();
        String[] dato=new String[5]; 
        
        try {
            while (rs.next()) {
                dato[0]=String.valueOf(rs.getInt("id_pro"));
                dato[1]=rs.getString("nombre_pro");
                dato[2]=rs.getString("descripcion_pro");
                dato[3]=String.valueOf(rs.getDouble("precio_pro"));
                dato[4]=String.valueOf(rs.getInt("stock_pro"));
                
                tbmodelo.addRow(dato);
            }
            tblProducto.setModel(tbmodelo);
        } catch (SQLException e) {
             System.out.println("error "+e.getMessage());
        }
    }
    
    void limpiar (){
        for (int i = 0; i < tblProducto.getRowCount() ; i++) {
            tbmodelo.removeRow(i);
            i= i - 1;
        }
    }
    
    
    void limpiarcajas(){
        txtid.setText("");
        txtnombre.setText("");
        txtdescripcion.setText("");
        txtprecio.setText("");
        txtstock.setText("");
        txtbuscarid.setText("");
        txtimagen.setText("");
        lblfoto.setIcon(null);
    }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtbuscarid;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtimagen;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
